openapi: 3.0.0
info:
  description: This api allow you to add and validate promo codes
  version: 1.0.0
  title: indy-tech-test
paths:
  /api/v1/promocodes:
    post:
      summary: Add a promo code
      description: |
        Allow to set various restrictions to a promo code
      operationId: addPromoCode
      requestBody:
        description: test
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Test"
      responses:
        "200":
          description: Promo code has been succesfully added
        "401":
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GlobalError"
              example:
                message: "You are not allowed to access this resource"
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GlobalError"
              example:
                message: "Validation failed for request.."

  /api/v1/promocodes/validate:
    post:
      summary: Validate a promo code
      description: |
        Validate a given promo code to apply its corresponding discount
      operationId: validatePromocode
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PromocodeValidateBody"
      responses:
        "200":
          description: Promo code is valid and give its corresponding discount
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PromocodeValidateResponse"
        "401":
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GlobalError"
              example:
                message: "You are not allowed to access this resource"
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GlobalError"
              example:
                message: "Validation failed for request.."

components:
  schemas:
    GlobalError:
      required:
        - message
      properties:
        message:
          type: string

    PromocodeValidateBody:
      type: object
      required:
        - promocode_name
      properties:
        promocode_name:
          type: string
        arguments:
          $ref: "#/components/schemas/PromocodeArgumentsBody"

    PromocodeArgumentsBody:
      type: object
      properties:
        age:
          type: number
          minimum: 0
          maximum: 130
        meteo:
          $ref: "#/components/schemas/Meteo"

    Meteo:
      type: object
      required:
        - town
      properties:
        town:
          type: string

    PromocodeValidateResponse:
      type: object
      required:
        - promocode_name
        - status
      properties:
        promocode_name:
          type: string
        status:
          type: string
          enum: ["accepted", "denied"]
        reasons:
          type: object

    reasons:
      type: object
      properties:
        meteo:
          type: string
        date:
          type: string
        age:
          type: string
